# Jupyter Notebook: Data cleaning

## Step 1: Install Required Libraries

First, ensure you have the necessary libraries installed. You can install them using the following command:

`pip install pandas numpy seaborn matplotlib`

## Step 2: Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import os

ModuleNotFoundError: No module named 'pandas'

## Step 3: Load the titanic dataset
Update the variable file_path to the path where you have your data.

In [45]:
df = pd.read_csv(os.path.join('titanic.csv'))

# Visualizing the first few rows of the dataset
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Step 4: Understanding the Data
Check dataset information, including data types and non-null counts
This helps us identify missing values and understand the data format

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  892 non-null    int64
 1   Survived     892 non-null    int64
 2   Pclass       892 non-null    int64
 3   Name         892 non-null    object
 4   Sex          892 non-null    object
 5   Age          715 non-null    float64
 6   SibSp        892 non-null    int64
 7   Parch        892 non-null    int64
 8   Ticket       892 non-null    object
 9   Fare         892 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     890 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.8+ KB

Check for missing values in each column to plan how to handle them

In [47]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          688
Embarked         2
dtype: int64

## Step 5: Removing missing values
For numerical columns (e.g., Age) we can fill missing values with the median.

In [48]:
# Fill missing 'Age' values with the median
df['Age'].fillna(df['Age'].median(), inplace=True)

C:\Users\FuentesL\AppData\Local\Temp\ipykernel_29244\1869324688.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

# Step 6: Remove irrelevant data
This dataset is used to predict if a passenger would survive the Titanic based on the information that we have about that passenger. However, some of the columns of the dataset contain information which is irrelevant to predict a passenger's chance of surviving. For example the passengner ID.

In [49]:
df.drop(['PassengerId'], axis=1, inplace=True)

df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Step 7: Convert categorical values to numerical
Some of the columns of the dataset contain categorical information like Sex and Embarked. However, machine learning algorithms require numerical input. We are going to transform the categorical values from the Sex column (female and male) to numerical by assigning a 0 to male and 1 to female.

In [60]:
# convert sex to numerical
df['Sex'].replace(['male', 'female'], [0, 1], inplace=True)

df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S

### Exercise 1

Determine what percentage of the cabin data is missing. Explain and justify what you think it should be done to handle those missing values. Then, write the corresponding code. 

<div style="text-align: right;">
  (1 mark)
</div>

<span style="color:red">Your answer goes here</span>

In [51]:
# Your answer goes here

### Exercise 2

Idenfity and justify which columns are irrelevant to determine if a passenger will survive the Titanic. Then, write the corresponding code. 

<div style="text-align: right;">
  (1 mark)
</div>

<span style="color:red">Your answer goes here</span>

In [52]:
# Your answer goes here

### Exercise 3

Transform the Embarked column from categorical to numerical.

<div style="text-align: right;">
  (1 mark)
</div>

### Exercise 4

Identify what type of data is the Embarked column. Explain why you can't fill in the missing values with the mean. Propose and justify an alternative and provide the corresponding code. 

<div style="text-align: right;">
  (2 marks)
</div>

<span style="color:red">Your answer goes here</span>

In [53]:
# Your answer goes here

### Exercise 5

Transform the Embarked column from categorical to numerical.

<div style="text-align: right;">
  (1 mark)
</div>

In [54]:
# Your answer goes here

### Exercise 6

Examine the Age column to identify any values that are impossible or unrealistic (e.g., negative ages or extreme values). Handle them appropriately.

<div style="text-align: right;">
  (2 marks)
</div>

In [55]:
# Your answer goes here

### Exercise 7

Calculate the percentage of passengers who survived the Titanic disaster.
(Hint: search for the `value_counts` function in the Pandas documentation)

<div style="text-align: right;">
  (1 mark)
</div>

In [56]:
# Your answer goes here

### Exercise 8

Check whether the dataset contains any duplicate rows. If duplicates are found, handle them appropriately.

<div style="text-align: right;">
  (1 mark)
</div>

In [57]:
# Your answer goes here

### Exercise 9

Previously, we filled missing age values using the average age. Propose two alternative methods for handling these missing values. For each method, explain how it might influence the results of future statistical analyses.

<div style="text-align: right;">
  (2 marks)
</div>

<span style="color:red">Your answer goes here</span>

### Exercise 10

Examine the Embarked column to determine whether the data is consistently formatted (for example, consistent use of uppercase and lowercase letters). If inconsistencies exist, clean the column to ensure uniform formatting.

<div style="text-align: right;">
  (2 marks)
</div>

In [58]:
# Your answer goes here

### Exercise 11

Save the cleaned dataset in a new csv file. Be careful not to overwrite the original file.

<div style="text-align: right;">
  (1 mark)
</div>

In [59]:
# Your answer goes here

## Extension 1

Create a new column called FamilySize by combining SibSp (siblings/spouses) and Parch (parents/children).

### Extension 2

Extract passenger titles from the Name column (e.g., Mr., Mrs., Miss.). Investigate whether there are any inconsistencies between a passenger’s title and their recorded gender or age, and describe any issues you find.